oauth:
  consumer_key: <%= ENV['FITBIT_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['FITBIT_CONSUMER_SECRET'] %>
  token: <%= ENV['FITBIT_TOKEN'] %>
  secret: <%= ENV['FITBIT_SECRET'] %>
  user_id: <%= ENV['FITBIT_USER_ID'] %>
